# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template:
  - trigger:
      - platform: time_pattern
        minutes: "/15"
    action:
      - service: homeassistant.update_entity
        target:
          entity_id:
            - climate.1ec942ca
            - climate.c62db069
            - climate.c63fd170
            - climate.c640155f
            - climate.c64015c4
    sensor:
      - name: "AC Living Room Temperatura"
        unique_id: ac_living_room_temp
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: "{{ state_attr('climate.1ec942ca', 'current_temperature') }}"
        availability: "{{ state_attr('climate.1ec942ca', 'current_temperature') is number }}"
        attributes:
          amostra: "{{ now().isoformat() }}"
      - name: "AC Cozinha Temperatura"
        unique_id: ac_cozinha_temp
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: "{{ state_attr('climate.c62db069', 'current_temperature') }}"
        availability: "{{ state_attr('climate.c62db069', 'current_temperature') is number }}"
        attributes:
          amostra: "{{ now().isoformat() }}"
      - name: "AC Office Temperatura"
        unique_id: ac_office_temp
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: "{{ state_attr('climate.c63fd170', 'current_temperature') }}"
        availability: "{{ state_attr('climate.c63fd170', 'current_temperature') is number }}"
        attributes:
          amostra: "{{ now().isoformat() }}"
      - name: "AC Suite Master Temperatura"
        unique_id: ac_suite_master_temp
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: "{{ state_attr('climate.c640155f', 'current_temperature') }}"
        availability: "{{ state_attr('climate.c640155f', 'current_temperature') is number }}"
        attributes:
          amostra: "{{ now().isoformat() }}"
      - name: "AC Kids Room Temperatura"
        unique_id: ac_kids_room_temp
        unit_of_measurement: "°C"
        device_class: temperature
        state_class: measurement
        state: "{{ state_attr('climate.c64015c4', 'current_temperature') }}"
        availability: "{{ state_attr('climate.c64015c4', 'current_temperature') is number }}"
        attributes:
          amostra: "{{ now().isoformat() }}"

recorder:
  purge_keep_days: 800
  commit_interval: 60
  include:
    entities:
      - sensor.ac_living_room_temperatura
      - sensor.ac_cozinha_temperatura
      - sensor.ac_office_temperatura
      - sensor.ac_suite_master_temperatura
      - sensor.ac_kids_room_temperatura
